### ISSUE TITLE
expanded logbook view

### ISSUE THREAD

**Issue by dschick** [MaxIV-KitsControls/Elogy#11]
Hej,

what do you think of having an expanded view of an entire logbook?
So in case you do not select a single entry of a logbook but "show all" you would get all entries shown in the right column.

I have the feeling that it is sometime easier to find some information, in case you do not want to use the search function.

Best

Daniel

**Comment by johanfforsberg** [comment]
Do you mean that instead of listing all the entries in the logbook in the middle column, we would show all entries chronologically in the right column? Hmm... not sure if that would be reasonable, unless the logbook was pretty small. For a large logbook, it might get pretty heavy for the frontend to render, and we'd have to load it incrementally anyway I think. Consider that a logbook that has been in use by dozens of people for keeping track of operations for a few years could contain thousands of entries.

Maybe we could use the brand new HTML export feature though! Let's say we basically make it possible to open a HTML export of the entire logbook in a new tab, maybe with some extra JS magic to load images on demand. It could still be quite a heavy operation though.

Otherwise, I think the search function should be improved if it doesn't help you find your stuff.

**Comment by dschick** [comment]
okay, I agree that it is a bad idea for large logbooks.
So maybe it is better to put more effort in improving the search functions.

Closing
